# Generated by Django 6.0.3 on 2026-03-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_doctor_user_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_to_appointment', to='core.timeslot'),
        ),
    ]
